import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  // routeTree.gen.ts is generated by @tanstack/router-plugin; ignoring it avoids
  // noise from knip not tracing route imports through the generated tree.
  ignore: ['src/components/ui/**', 'src/routeTree.gen.ts'],
  ignoreDependencies: ['tailwindcss', 'tw-animate-css'],
  // Service/DTO modules legitimately export helpers that are only referenced
  // within the same file (e.g. internal types used by exported types).
  ignoreExportsUsedInFile: true,
};

export default config;
