package config

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Config 本地 CLI 配置
type Config struct {
	ServerURL    string
	AccessToken  string
	RefreshToken string

	// envOverridden 记录哪些字段由环境变量提供，Save 时会跳过持久化以避免把临时 SHADMIN_SERVER 写入磁盘文件。
	envOverridden map[string]bool
}

// Path 返回配置文件路径
// 优先使用 SHADMIN_CONFIG；默认使用 cli/.env（在 cli 目录运行时使用当前 .env）。
func Path() (string, error) {
	if p := os.Getenv("SHADMIN_CONFIG"); p != "" {
		return p, nil
	}
	if _, err := os.Stat("cli"); err == nil {
		return filepath.Join("cli", ".env"), nil
	}
	return ".env", nil
}

// Load 读取配置文件；文件不存在时返回空 Config（不报错）
func Load() (*Config, error) {
	p, err := Path()
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(p)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return &Config{}, nil
		}
		return nil, fmt.Errorf("read config %s: %w", p, err)
	}
	c, err := parseEnvConfig(data)
	if err != nil {
		return nil, fmt.Errorf("parse config %s: %w", p, err)
	}
	applyEnvOverrides(c)
	return c, nil
}

func applyEnvOverrides(c *Config) {
	if c.envOverridden == nil {
		c.envOverridden = map[string]bool{}
	}
	if v := os.Getenv("SHADMIN_SERVER"); v != "" {
		c.ServerURL = v
		c.envOverridden["SHADMIN_SERVER"] = true
	}
}

// ApplyServerOverride applies --server. Login persists it as initial setup;
// other commands keep it as a one-shot override so token refreshes do not rewrite config.
func ApplyServerOverride(c *Config, serverURL string, persist bool) {
	if serverURL == "" {
		return
	}
	c.ServerURL = serverURL
	if c.envOverridden == nil {
		c.envOverridden = map[string]bool{}
	}
	if persist {
		delete(c.envOverridden, "SHADMIN_SERVER")
		return
	}
	c.envOverridden["SHADMIN_SERVER"] = true
}

// Save 以 0600 权限写回配置文件
// 由环境变量提供的字段不会被持久化到磁盘，避免把临时凭据写入用户配置。
func Save(c *Config) error {
	p, err := Path()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o700); err != nil {
		return fmt.Errorf("mkdir config dir: %w", err)
	}

	toWrite := *c
	toWrite.envOverridden = nil
	if len(c.envOverridden) > 0 {
		// 读取磁盘上已有的值，恢复 env 覆盖前的字段，避免把环境变量写入磁盘
		if data, rerr := os.ReadFile(p); rerr == nil {
			if disk, perr := parseEnvConfig(data); perr == nil {
				if c.envOverridden["SHADMIN_SERVER"] {
					toWrite.ServerURL = disk.ServerURL
				}
			}
		} else if errors.Is(rerr, os.ErrNotExist) {
			if c.envOverridden["SHADMIN_SERVER"] {
				toWrite.ServerURL = ""
			}
		}
	}

	data := marshalEnvConfig(&toWrite)
	if err := os.WriteFile(p, data, 0o600); err != nil {
		return fmt.Errorf("write config %s: %w", p, err)
	}
	return nil
}

func parseEnvConfig(data []byte) (*Config, error) {
	c := &Config{}
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			return nil, fmt.Errorf("line %d: expected KEY=VALUE", lineNumber)
		}
		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		if unquoted, err := strconv.Unquote(value); err == nil {
			value = unquoted
		}
		switch key {
		case "SHADMIN_SERVER":
			c.ServerURL = value
		case "SHADMIN_TOKEN":
			c.AccessToken = value
		case "SHADMIN_REFRESH_TOKEN":
			c.RefreshToken = value
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return c, nil
}

func marshalEnvConfig(c *Config) []byte {
	var b strings.Builder
	b.WriteString("# shadmin-cli local config\n")
	b.WriteString("# Generated by shadmin-cli; keep this file private.\n\n")
	writeEnv(&b, "SHADMIN_SERVER", c.ServerURL)
	writeEnvIfSet(&b, "SHADMIN_TOKEN", c.AccessToken)
	writeEnvIfSet(&b, "SHADMIN_REFRESH_TOKEN", c.RefreshToken)
	return []byte(b.String())
}

func writeEnvIfSet(b *strings.Builder, key string, value string) {
	if value == "" {
		return
	}
	writeEnv(b, key, value)
}

func writeEnv(b *strings.Builder, key string, value string) {
	if value == "" {
		fmt.Fprintf(b, "%s=\n", key)
		return
	}
	if strings.ContainsAny(value, " \t\r\n#\"'\\") {
		fmt.Fprintf(b, "%s=%s\n", key, strconv.Quote(value))
		return
	}
	fmt.Fprintf(b, "%s=%s\n", key, value)
}

// Clear 删除配置中的令牌字段并写回
func Clear() error {
	c, err := Load()
	if err != nil {
		return err
	}
	c.AccessToken = ""
	c.RefreshToken = ""
	return Save(c)
}
